// Package keygen writes the file that re-exports Ebitengine's key constants
// as ggui's own, so that a widget names a key without importing Ebitengine.
//
// It asks Ebitengine for the names rather than reading its source: Key.String
// returns the canonical spelling of each key, so the constants deprecated in
// favour of another spelling cannot come out of it, and a new key appears the
// moment the dependency is updated and the file regenerated.
package keygen

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/hajimehoshi/ebiten/v2"
)

// Generate returns the source of the key constant file, gofmt'd.
func Generate() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`// Code generated by internal/tools/keygen; DO NOT EDIT.

package ggui

import "github.com/hajimehoshi/ebiten/v2"

// The keys Ebitengine reports, by their US layout names. A key is a
// physical place on the keyboard, not the character it produces.
const (
`)
	for k := ebiten.Key(0); k <= ebiten.KeyMax; k++ {
		if name := k.String(); name != "" {
			fmt.Fprintf(&b, "\tKey%s KeyboardKey = ebiten.Key%s\n", name, name)
		}
	}
	b.WriteString(")\n")
	return format.Source(b.Bytes())
}
